import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Providers from "@/providers";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const viewport = {
    themeColor: "#DB65FB",
};

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html>
            <body className={`${inter.className} bg-neutral-900`}>
                <Header />
                <Providers>
                    {children}
                </Providers>
            </body>
        </html>
    );
}
